### ISSUE TITLE
mba6x_bl ebuild fails

### ISSUE THREAD

**Issue by eugenecormier** [chrisperelstein/gentoo-overlay#2]
when I add this to my local overlay, and keyword and emerge I get the following:

emerge -av mba6x_bl

These are the packages that would be merged, in order:

Calculating dependencies            ... done!  
[ebuild  N    *] x11-drivers/mba6x_bl-9999::Eugenes-Overlay  0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] 

> > > Verifying ebuild manifests
> > > Emerging (1 of 1) x11-drivers/mba6x_bl-9999::Eugenes-Overlay
> > > Failed to emerge x11-drivers/mba6x_bl-9999, Log file:
> > >  '/var/tmp/portage/x11-drivers/mba6x_bl-9999/temp/build.log'
> > > Jobs: 0 of 1 complete, 1 failed                 Load avg: 0.17, 0.14, 0.19
> > > - Package:    x11-drivers/mba6x_bl-9999
> > > - Repository: Eugenes-Overlay
> > > - USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
> > > - FEATURES:   preserve-libs sandbox userpriv usersandbox
> > > - Determining the location of the kernel source code
> > > - Found kernel source directory:
> > > -     /usr/src/linux
> > > - Found kernel object directory:
> > > -     /lib/modules/4.2.0-gentoo-r1/build
> > > - Found sources for kernel version:
> > > -     4.2.0-gentoo-r1
> > >   Unpacking source...
> > > - Fetching git://github.com/patjak/mba6x_bl.git ...
> > >   git fetch git://github.com/patjak/mba6x_bl.git +HEAD:refs/git-r3/HEAD
> > >   git symbolic-ref refs/git-r3/x11-drivers/mba6x_bl/0/**main** refs/heads/master
> > > - Checking out git://github.com/patjak/mba6x_bl.git to /var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999 ...
> > >   git checkout --quiet master
> > >   GIT update -->
> > >   repository:               git://github.com/patjak/mba6x_bl.git
> > >   at the commit:            fc64de1442a47185c49aba2dc445016abb418207
> > >   Source unpacked in /var/tmp/portage/x11-drivers/mba6x_bl-9999/work
> > >   Preparing source in /var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999 ...
> > >   Source prepared.
> > >   Configuring source in /var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999 ...
> > >   Source configured.
> > >   Compiling source in /var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999 ...
> > >   ln: failed to create symbolic link ‘Module.symvers’: File exists
> > > - Preparing mba6x_bl module
> > >   make -j4 HOSTCC=x86_64-pc-linux-gnu-gcc CROSS_COMPILE=x86_64-pc-linux-gnu- 'LDFLAGS=-m elf_x86_64' clean all 
> > >   make -C /lib/modules/4.2.0-gentoo-r1/build M=/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999 clean
> > >   make -C /lib/modules/4.2.0-gentoo-r1/build M=/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999 modules
> > >   make[1]: Entering directory '/usr/src/linux-4.2.0-gentoo-r1'
> > >   make[1]: Entering directory '/usr/src/linux-4.2.0-gentoo-r1'
> > >   CLEAN   /var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999/Module.symvers
> > >   make[1]: Leaving directory '/usr/src/linux-4.2.0-gentoo-r1'
> > >   CC [M]  /var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999/mba6x_bl.o
> > >   /var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999/mba6x_bl.c: In function 'platform_probe':
> > >   /var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999/mba6x_bl.c:336:2: error: implicit declaration of function 'acpi_video_dmi_promote_vendor' [-Werror=implicit-function-declaration]
> > >   acpi_video_dmi_promote_vendor();
> > >   ^
> > >   cc1: some warnings being treated as errors
> > >   scripts/Makefile.build:264: recipe for target '/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999/mba6x_bl.o' failed
> > >   make[2]: **\* [/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999/mba6x_bl.o] Error 1
> > >   Makefile:1386: recipe for target '_module_/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999' failed
> > >   make[1]: **\* [_module_/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999] Error 2
> > >   make[1]: Leaving directory '/usr/src/linux-4.2.0-gentoo-r1'
> > >   Makefile:8: recipe for target 'all' failed
> > >   make: **\* [all] Error 2
> > > - ERROR: x11-drivers/mba6x_bl-9999::Eugenes-Overlay failed (compile phase):
> > > -   emake failed
> > > - 
> > > - If you need support, post the output of `emerge --info '=x11-drivers/mba6x_bl-9999::Eugenes-Overlay'`,
> > > - the complete build log and the output of `emerge -pqv '=x11-drivers/mba6x_bl-9999::Eugenes-Overlay'`.
> > > - The complete build log is located at '/var/tmp/portage/x11-drivers/mba6x_bl-9999/temp/build.log'.
> > > - The ebuild environment file is located at '/var/tmp/portage/x11-drivers/mba6x_bl-9999/temp/environment'.
> > > - Working directory: '/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999'
> > > - S: '/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999'
- Messages for package x11-drivers/mba6x_bl-9999:
- ERROR: x11-drivers/mba6x_bl-9999::Eugenes-Overlay failed (compile phase):
-   emake failed
- 
- If you need support, post the output of `emerge --info '=x11-drivers/mba6x_bl-9999::Eugenes-Overlay'`,
- the complete build log and the output of `emerge -pqv '=x11-drivers/mba6x_bl-9999::Eugenes-Overlay'`.
- The complete build log is located at '/var/tmp/portage/x11-drivers/mba6x_bl-9999/temp/build.log'.
- The ebuild environment file is located at '/var/tmp/portage/x11-drivers/mba6x_bl-9999/temp/environment'.
- Working directory: '/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999'
- S: '/var/tmp/portage/x11-drivers/mba6x_bl-9999/work/mba6x_bl-9999'

**Comment by eugenecormier** [comment]
sorry, this is a problem with the source and kernel >=4.2
https://github.com/patjak/mba6x_bl/issues/32

**Comment by chrisperelstein** [comment]
Looks like this is fixed as of patjak/mba6x_bl#34.
